/**
 * ULTIMATE KNOWLEDGE QUIZ - Question Bank
 * 25 questions per category. Script shuffles and randomly picks 10 per game.
 */

const quizData = {
  science: [
    { question: "Which planet is known as the Red Planet?", options: ["Venus", "Mars", "Jupiter", "Saturn"], answer: "Mars" },
    { question: "What gas do plants absorb from the atmosphere?", options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], answer: "Carbon Dioxide" },
    { question: "What is the boiling point of water at sea level?", options: ["50°C", "75°C", "100°C", "125°C"], answer: "100°C" },
    { question: "What is the largest organ in the human body?", options: ["Brain", "Heart", "Skin", "Liver"], answer: "Skin" },
    { question: "What force pulls objects toward the Earth?", options: ["Magnetism", "Friction", "Gravity", "Inertia"], answer: "Gravity" },
    { question: "What is the chemical symbol for gold?", options: ["Go", "Gd", "Au", "Ag"], answer: "Au" },
    { question: "Which gas is most abundant in Earth's atmosphere?", options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Argon"], answer: "Nitrogen" },
    { question: "What type of rock is formed from cooled lava?", options: ["Sedimentary", "Metamorphic", "Igneous", "Limestone"], answer: "Igneous" },
    { question: "What is the speed of light in vacuum (approximately)?", options: ["300,000 km/s", "150,000 km/s", "500,000 km/s", "100,000 km/s"], answer: "300,000 km/s" },
    { question: "Which element has the atomic number 1?", options: ["Helium", "Hydrogen", "Carbon", "Oxygen"], answer: "Hydrogen" },
    { question: "What is the chemical symbol for sodium?", options: ["So", "Sd", "Na", "Nm"], answer: "Na" },
    { question: "Which organ pumps blood through the body?", options: ["Lungs", "Heart", "Liver", "Kidney"], answer: "Heart" },
    { question: "What is H₂O commonly known as?", options: ["Salt", "Water", "Sugar", "Vinegar"], answer: "Water" },
    { question: "What is the smallest unit of life?", options: ["Atom", "Cell", "Molecule", "Tissue"], answer: "Cell" },
    { question: "Which planet is known for its rings?", options: ["Jupiter", "Mars", "Saturn", "Uranus"], answer: "Saturn" },
    { question: "What type of energy is stored in a battery?", options: ["Kinetic", "Chemical", "Thermal", "Sound"], answer: "Chemical" },
    { question: "How many bones are in the adult human body (approx)?", options: ["186", "206", "226", "246"], answer: "206" },
    { question: "What is the main gas in the Sun?", options: ["Helium", "Hydrogen", "Oxygen", "Nitrogen"], answer: "Hydrogen" },
    { question: "Which vitamin is produced when skin is exposed to sunlight?", options: ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K"], answer: "Vitamin D" },
    { question: "What is the study of earthquakes called?", options: ["Meteorology", "Seismology", "Volcanology", "Geology"], answer: "Seismology" },
    { question: "Which metal is liquid at room temperature?", options: ["Gold", "Mercury", "Silver", "Copper"], answer: "Mercury" },
    { question: "What is the powerhouse of the cell?", options: ["Nucleus", "Ribosome", "Mitochondria", "Golgi body"], answer: "Mitochondria" },
    { question: "What is the pH of pure water?", options: ["5", "6", "7", "8"], answer: "7" },
    { question: "Which gas do we breathe out the most?", options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Argon"], answer: "Nitrogen" },
    { question: "What is the hardest mineral on the Mohs scale?", options: ["Ruby", "Diamond", "Topaz", "Quartz"], answer: "Diamond" }
  ],

  mathematics: [
    { question: "What is 15% of 200?", options: ["20", "25", "30", "35"], answer: "30" },
    { question: "What is the value of Pi (π) approximately?", options: ["3.14", "3.41", "2.14", "4.13"], answer: "3.14" },
    { question: "What is 7 × 8?", options: ["54", "56", "58", "64"], answer: "56" },
    { question: "What is the square root of 144?", options: ["10", "11", "12", "14"], answer: "12" },
    { question: "Solve for x: 2x + 5 = 15", options: ["x = 3", "x = 5", "x = 7", "x = 10"], answer: "x = 5" },
    { question: "What is the area of a rectangle with length 8 and width 5?", options: ["13", "26", "40", "80"], answer: "40" },
    { question: "What is 3³ (3 cubed)?", options: ["9", "12", "27", "81"], answer: "27" },
    { question: "How many degrees are in a right angle?", options: ["45", "90", "180", "360"], answer: "90" },
    { question: "What is the next number: 2, 4, 8, 16, ___?", options: ["24", "32", "28", "36"], answer: "32" },
    { question: "What is 25 × 4?", options: ["90", "95", "100", "105"], answer: "100" },
    { question: "What is 144 ÷ 12?", options: ["10", "11", "12", "14"], answer: "12" },
    { question: "What is the perimeter of a square with side 5?", options: ["15", "20", "25", "30"], answer: "20" },
    { question: "What is 15 + 27?", options: ["40", "41", "42", "43"], answer: "42" },
    { question: "How many sides does a hexagon have?", options: ["5", "6", "7", "8"], answer: "6" },
    { question: "What is 1000 − 237?", options: ["763", "773", "737", "753"], answer: "763" },
    { question: "What is ½ + ½?", options: ["1", "2", "1/4", "3/4"], answer: "1" },
    { question: "What is 9 × 9?", options: ["72", "81", "90", "99"], answer: "81" },
    { question: "What is 20% of 50?", options: ["5", "10", "15", "25"], answer: "10" },
    { question: "What is the next number: 1, 3, 6, 10, ___?", options: ["14", "15", "16", "18"], answer: "15" },
    { question: "How many degrees are in a triangle?", options: ["90", "180", "270", "360"], answer: "180" },
    { question: "What is 17 × 3?", options: ["41", "51", "61", "71"], answer: "51" },
    { question: "What is the square root of 81?", options: ["7", "8", "9", "10"], answer: "9" },
    { question: "What is 5! (5 factorial)?", options: ["100", "120", "60", "24"], answer: "120" },
    { question: "What is ¾ of 80?", options: ["40", "50", "60", "70"], answer: "60" },
    { question: "What is 2⁴ (2 to the power of 4)?", options: ["8", "16", "32", "64"], answer: "16" }
  ],

  computer: [
    { question: "What does CPU stand for?", options: ["Central Processing Unit", "Computer Personal Unit", "Central Program Utility", "Central Processor Unifier"], answer: "Central Processing Unit" },
    { question: "Which programming language is known for web development?", options: ["Java", "JavaScript", "C++", "Python"], answer: "JavaScript" },
    { question: "What does HTML stand for?", options: ["Hyper Text Markup Language", "High Tech Modern Language", "Home Tool Markup Language", "Hyper Transfer Markup Language"], answer: "Hyper Text Markup Language" },
    { question: "What is the main function of RAM?", options: ["Long-term storage", "Temporary data storage", "Display graphics", "Connect to internet"], answer: "Temporary data storage" },
    { question: "Which symbol is used for single-line comments in JavaScript?", options: ["/* */", "//", "#", "--"], answer: "//" },
    { question: "What does URL stand for?", options: ["Uniform Resource Locator", "Universal Reference Link", "Unified Resource Locator", "Unique Resource Location"], answer: "Uniform Resource Locator" },
    { question: "What does SSD stand for?", options: ["Solid State Drive", "Super Speed Disk", "System Storage Device", "Secure Storage Drive"], answer: "Solid State Drive" },
    { question: "Which company created the Windows operating system?", options: ["Apple", "Google", "Microsoft", "IBM"], answer: "Microsoft" },
    { question: "What does VPN stand for?", options: ["Virtual Private Network", "Very Protected Network", "Visual Personal Node", "Verified Private Net"], answer: "Virtual Private Network" },
    { question: "Which protocol is used to send email?", options: ["FTP", "HTTP", "SMTP", "TCP"], answer: "SMTP" },
    { question: "What does CSS stand for?", options: ["Cascading Style Sheets", "Computer Style System", "Creative Style Syntax", "Code Style Sheet"], answer: "Cascading Style Sheets" },
    { question: "What is 1 byte equal to?", options: ["4 bits", "8 bits", "16 bits", "32 bits"], answer: "8 bits" },
    { question: "Which browser engine does Chrome use?", options: ["Gecko", "WebKit", "Blink", "Trident"], answer: "Blink" },
    { question: "What does API stand for?", options: ["Application Programming Interface", "Advanced Program Input", "Automated Protocol Interface", "Application Process Integration"], answer: "Application Programming Interface" },
    { question: "Which language is used for styling web pages?", options: ["HTML", "JavaScript", "CSS", "Python"], answer: "CSS" },
    { question: "What does HTTP stand for?", options: ["HyperText Transfer Protocol", "High Transfer Text Protocol", "Hyper Transfer Text Protocol", "High Text Transfer Protocol"], answer: "HyperText Transfer Protocol" },
    { question: "What is the default port for HTTPS?", options: ["80", "443", "8080", "22"], answer: "443" },
    { question: "Which data structure uses LIFO?", options: ["Queue", "Stack", "Array", "LinkedList"], answer: "Stack" },
    { question: "What does GUI stand for?", options: ["Graphical User Interface", "General User Input", "Graphic Utility Interface", "Global User Interaction"], answer: "Graphical User Interface" },
    { question: "Which company developed the Android OS?", options: ["Apple", "Microsoft", "Google", "Samsung"], answer: "Google" },
    { question: "What does IDE stand for in programming?", options: ["Integrated Development Environment", "Internal Debug Editor", "Interactive Design Engine", "Integrated Data Exchange"], answer: "Integrated Development Environment" },
    { question: "How many bits are in 1 kilobyte (KB)?", options: ["8000", "8192", "1000", "1024"], answer: "8192" },
    { question: "Which symbol is used for multiplication in most programming languages?", options: ["×", "*", "x", "#"], answer: "*" },
    { question: "What does SQL stand for?", options: ["Structured Query Language", "Simple Query Language", "Standard Question Logic", "System Query Link"], answer: "Structured Query Language" },
    { question: "What is the file extension for a JavaScript file?", options: [".java", ".js", ".script", ".javascript"], answer: ".js" }
  ],

  football: [
    { question: "How many players are on a football (soccer) team on the field?", options: ["9", "10", "11", "12"], answer: "11" },
    { question: "What is the name of the trophy for the FIFA World Cup?", options: ["Jules Rimet Trophy", "World Cup Trophy", "FIFA Trophy", "Golden Cup"], answer: "World Cup Trophy" },
    { question: "How long is a standard football match (excluding extra time)?", options: ["80 minutes", "90 minutes", "100 minutes", "120 minutes"], answer: "90 minutes" },
    { question: "Which country has won the most FIFA World Cups?", options: ["Germany", "Italy", "Brazil", "Argentina"], answer: "Brazil" },
    { question: "What color card indicates a player is sent off?", options: ["Yellow", "Red", "Orange", "Black"], answer: "Red" },
    { question: "Which position is traditionally number 10?", options: ["Goalkeeper", "Defender", "Midfielder", "Striker"], answer: "Midfielder" },
    { question: "What is the diameter of a football (soccer ball) in cm (approx)?", options: ["18–20", "20–22", "22–24", "24–26"], answer: "22–24" },
    { question: "In which country did modern football originate?", options: ["France", "Brazil", "England", "Italy"], answer: "England" },
    { question: "How many substitutes are allowed in a standard FIFA match?", options: ["3", "5", "7", "9"], answer: "5" },
    { question: "What does the 'D' on the edge of the penalty area mark?", options: ["Penalty arc", "Goal area", "Corner arc", "Centre circle"], answer: "Penalty arc" },
    { question: "Which country won the FIFA World Cup in 2018?", options: ["Germany", "France", "Brazil", "Croatia"], answer: "France" },
    { question: "What is a 'hat-trick' in football?", options: ["3 goals in one match by one player", "Saving 3 penalties", "3 assists in one match", "Winning 3 trophies"], answer: "3 goals in one match by one player" },
    { question: "Which club has won the most UEFA Champions League titles?", options: ["Barcelona", "AC Milan", "Real Madrid", "Bayern Munich"], answer: "Real Madrid" },
    { question: "What is the name of the English top-flight league?", options: ["Championship", "Premier League", "League One", "FA Cup"], answer: "Premier League" },
    { question: "How wide is a football goal in meters (approx)?", options: ["6.4", "7.32", "8", "9.15"], answer: "7.32" },
    { question: "Which country hosted the 2022 FIFA World Cup?", options: ["Russia", "Qatar", "Brazil", "South Africa"], answer: "Qatar" },
    { question: "What is 'offside'?", options: ["A foul", "A position rule when receiving the ball", "A type of pass", "A throw-in"], answer: "A position rule when receiving the ball" },
    { question: "Which Italian club is known as 'The Old Lady'?", options: ["AC Milan", "Inter Milan", "Juventus", "Roma"], answer: "Juventus" },
    { question: "Who has scored the most goals in World Cup history?", options: ["Pelé", "Miroslav Klose", "Ronaldo", "Müller"], answer: "Miroslav Klose" },
    { question: "What is the minimum number of players needed to start a match?", options: ["7", "9", "10", "11"], answer: "7" },
    { question: "Which country won the first ever World Cup in 1930?", options: ["Brazil", "Uruguay", "Argentina", "Italy"], answer: "Uruguay" },
    { question: "What is a 'clean sheet'?", options: ["No goals conceded", "No fouls", "No offsides", "No cards"], answer: "No goals conceded" },
    { question: "Which Spanish club plays at the Camp Nou?", options: ["Real Madrid", "Atlético Madrid", "Barcelona", "Sevilla"], answer: "Barcelona" },
    { question: "How many points for a win in league football?", options: ["1", "2", "3", "4"], answer: "3" },
    { question: "What is the penalty spot distance from the goal line (meters)?", options: ["9", "10", "11", "12"], answer: "11" }
  ],

  cricket: [
    { question: "How many players are in a cricket team?", options: ["9", "10", "11", "12"], answer: "11" },
    { question: "How many runs is a boundary (ball crossing the rope)?", options: ["2", "4", "6", "8"], answer: "4" },
    { question: "What is a 'duck' in cricket?", options: ["A type of shot", "Getting out for 0 runs", "A type of delivery", "A fielding position"], answer: "Getting out for 0 runs" },
    { question: "How many balls are in one over?", options: ["4", "5", "6", "8"], answer: "6" },
    { question: "Which country invented cricket?", options: ["Australia", "India", "England", "South Africa"], answer: "England" },
    { question: "What is the longest format of cricket called?", options: ["T20", "ODI", "Test Match", "One Day"], answer: "Test Match" },
    { question: "How many runs for a ball hit over the boundary without bouncing?", options: ["4", "6", "8", "10"], answer: "6" },
    { question: "What is the name of the annual England–Australia Test series?", options: ["The Derby", "The Ashes", "The Cup", "The Shield"], answer: "The Ashes" },
    { question: "Which country has won the most Cricket World Cups (ODI)?", options: ["India", "England", "Australia", "West Indies"], answer: "Australia" },
    { question: "What is 'LBW' short for?", options: ["Leg Before Wicket", "Long Boundary Win", "Last Ball Wicket", "Lead Bowler Win"], answer: "Leg Before Wicket" },
    { question: "How many stumps are in a set of wickets?", options: ["2", "3", "4", "6"], answer: "3" },
    { question: "What is a 'googly' in cricket?", options: ["A type of run", "A spin delivery that turns the other way", "A fielding position", "A type of bat"], answer: "A spin delivery that turns the other way" },
    { question: "In T20 cricket, how many overs per side?", options: ["10", "20", "50", "90"], answer: "20" },
    { question: "Who is known as the 'God of Cricket' in India?", options: ["Kapil Dev", "Sachin Tendulkar", "MS Dhoni", "Virat Kohli"], answer: "Sachin Tendulkar" },
    { question: "What is a 'maiden over'?", options: ["An over with no runs scored", "An over with a wicket", "The first over of the innings", "An over with 6 runs"], answer: "An over with no runs scored" },
    { question: "Which country hosted the first T20 World Cup?", options: ["India", "England", "South Africa", "Australia"], answer: "South Africa" },
    { question: "What is the maximum number of overs a bowler can bowl in an ODI?", options: ["8", "10", "12", "15"], answer: "10" },
    { question: "What does 'stumped' mean?", options: ["Run out by the wicketkeeper", "Bowled", "Caught", "Hit wicket"], answer: "Run out by the wicketkeeper" },
    { question: "Which trophy is awarded for the India–Pakistan Test series?", options: ["Border-Gavaskar", "Ashes", "No specific trophy", "Freedom Trophy"], answer: "No specific trophy" },
    { question: "What is a 'yorker'?", options: ["A ball that bounces near the batsman's feet", "A bouncer", "A full toss", "A wide"], answer: "A ball that bounces near the batsman's feet" },
    { question: "How many runs is a 'single'?", options: ["1", "2", "3", "4"], answer: "1" },
    { question: "Which Indian cricketer has the most Test runs?", options: ["Sunil Gavaskar", "Sachin Tendulkar", "Rahul Dravid", "Virat Kohli"], answer: "Sachin Tendulkar" },
    { question: "What is the name of the cricket ground at Lord's?", options: ["The Oval", "Lord's Cricket Ground", "Headingley", "Edgbaston"], answer: "Lord's Cricket Ground" },
    { question: "In a Test match, how many innings can each team have?", options: ["1", "2", "3", "Unlimited"], answer: "2" },
    { question: "What is a 'nightwatchman' in cricket?", options: ["A lower-order batter sent in to protect a main batter", "A type of bowler", "A fielder", "A referee"], answer: "A lower-order batter sent in to protect a main batter" }
  ],

  general: [
    { question: "What is the capital of France?", options: ["London", "Berlin", "Paris", "Madrid"], answer: "Paris" },
    { question: "How many continents are there?", options: ["5", "6", "7", "8"], answer: "7" },
    { question: "What is the largest ocean on Earth?", options: ["Atlantic", "Indian", "Arctic", "Pacific"], answer: "Pacific" },
    { question: "In which year did World War II end?", options: ["1943", "1944", "1945", "1946"], answer: "1945" },
    { question: "Who painted the Mona Lisa?", options: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Michelangelo"], answer: "Leonardo da Vinci" },
    { question: "What is the hardest natural substance on Earth?", options: ["Gold", "Iron", "Diamond", "Platinum"], answer: "Diamond" },
    { question: "Which planet is closest to the Sun?", options: ["Venus", "Earth", "Mercury", "Mars"], answer: "Mercury" },
    { question: "What is the largest country by area?", options: ["USA", "China", "Russia", "Canada"], answer: "Russia" },
    { question: "How many strings does a standard guitar have?", options: ["4", "5", "6", "8"], answer: "6" },
    { question: "What is the main ingredient in bread?", options: ["Corn", "Rice", "Wheat flour", "Potato"], answer: "Wheat flour" },
    { question: "What is the capital of Egypt?", options: ["Cairo", "Alexandria", "Luxor", "Giza"], answer: "Cairo" },
    { question: "How many days are in a leap year?", options: ["364", "365", "366", "367"], answer: "366" },
    { question: "Which animal is the symbol of the Olympic Games?", options: ["Eagle", "Lion", "Five rings", "Dove"], answer: "Five rings" },
    { question: "What is the largest mammal on Earth?", options: ["Elephant", "Blue whale", "Giraffe", "Polar bear"], answer: "Blue whale" },
    { question: "In which country is the Great Barrier Reef?", options: ["Indonesia", "Philippines", "Australia", "Thailand"], answer: "Australia" },
    { question: "What is the main language of Brazil?", options: ["Spanish", "Portuguese", "French", "English"], answer: "Portuguese" },
    { question: "How many sides does a stop sign have?", options: ["6", "8", "10", "12"], answer: "8" },
    { question: "Which fruit is known as the 'king of fruits' in Southeast Asia?", options: ["Mango", "Durian", "Papaya", "Pineapple"], answer: "Durian" },
    { question: "What is the smallest prime number?", options: ["0", "1", "2", "3"], answer: "2" },
    { question: "Which planet is known as the 'Giant Red Spot'?", options: ["Mars", "Jupiter", "Saturn", "Neptune"], answer: "Jupiter" },
    { question: "What is the chemical symbol for iron?", options: ["Ir", "Fe", "In", "I"], answer: "Fe" },
    { question: "How many hours are in a day?", options: ["12", "24", "36", "48"], answer: "24" },
    { question: "Which country is home to the kangaroo?", options: ["New Zealand", "Australia", "South Africa", "India"], answer: "Australia" },
    { question: "What is the opposite of 'antonym'?", options: ["Synonym", "Homonym", "Acronym", "Pseudonym"], answer: "Synonym" },
    { question: "Which organ is responsible for filtering blood?", options: ["Heart", "Liver", "Kidney", "Lungs"], answer: "Kidney" }
  ],

  nepalHistory: [
    { question: "In which year was Nepal unified by King Prithvi Narayan Shah?", options: ["1768", "1769", "1770", "1775"], answer: "1768" },
    { question: "Who is known as the founder of modern Nepal?", options: ["King Tribhuvan", "King Prithvi Narayan Shah", "King Mahendra", "King Birendra"], answer: "King Prithvi Narayan Shah" },
    { question: "From which kingdom did Prithvi Narayan Shah start his unification campaign?", options: ["Kathmandu", "Gorkha", "Patan", "Bhaktapur"], answer: "Gorkha" },
    { question: "In which year did the Kot Parva (Kot Massacre) take place?", options: ["1843", "1846", "1850", "1857"], answer: "1846" },
    { question: "Who established the Rana rule in Nepal?", options: ["Jang Bahadur Rana", "Chandra Shumsher", "Bhimsen Thapa", "Mathabar Singh"], answer: "Jang Bahadur Rana" },
    { question: "In which year did the Rana regime end and democracy begin?", options: ["1947", "1950", "1951", "1960"], answer: "1951" },
    { question: "Who was the last Rana Prime Minister of Nepal?", options: ["Mohan Shumsher", "Chandra Shumsher", "Juddha Shumsher", "Padma Shumsher"], answer: "Mohan Shumsher" },
    { question: "In which year did King Tribhuvan escape to India during the revolution?", options: ["1947", "1950", "1951", "1948"], answer: "1950" },
    { question: "When was the first democratic election held in Nepal?", options: ["1956", "1959", "1960", "1990"], answer: "1959" },
    { question: "Who was the first elected Prime Minister of Nepal?", options: ["B.P. Koirala", "Matrika Prasad Koirala", "Tanka Prasad Acharya", "K.I. Singh"], answer: "B.P. Koirala" },
    { question: "In which year did King Mahendra introduce the Panchayat system?", options: ["1959", "1960", "1961", "1962"], answer: "1960" },
    { question: "When did the People's Movement (Jana Andolan) I restore multiparty democracy?", options: ["1988", "1989", "1990", "1991"], answer: "1990" },
    { question: "In which year did the Maoist insurgency (People's War) begin in Nepal?", options: ["1994", "1996", "2001", "2006"], answer: "1996" },
    { question: "When did the Comprehensive Peace Agreement end the civil war in Nepal?", options: ["2004", "2005", "2006", "2007"], answer: "2006" },
    { question: "In which year was the monarchy abolished in Nepal?", options: ["2006", "2007", "2008", "2015"], answer: "2008" },
    { question: "When was the new Constitution of Nepal promulgated?", options: ["2012", "2015", "2017", "2018"], answer: "2015" },
    { question: "Who was the first President of the Federal Democratic Republic of Nepal?", options: ["Ram Baran Yadav", "Bidya Devi Bhandari", "Parmanand Jha", "None of these"], answer: "Ram Baran Yadav" },
    { question: "Which treaty signed in 1816 defined Nepal's boundaries with British India?", options: ["Sugauli Treaty", "Treaty of Kathmandu", "Treaty of Gorkha", "Treaty of Nepal"], answer: "Sugauli Treaty" },
    { question: "Who was the Prime Minister during the Kot Massacre?", options: ["Jang Bahadur Rana", "Fateh Jung Shah", "Gagan Singh", "Abhiman Singh"], answer: "Jang Bahadur Rana" },
    { question: "Which dynasty ruled Nepal before the Shah dynasty's unification?", options: ["Malla", "Lichchhavi", "Kirant", "Gopal"], answer: "Malla" },
    { question: "In which century did the Lichchhavi period flourish in Nepal?", options: ["2nd–3rd century", "4th–9th century", "10th–12th century", "13th–14th century"], answer: "4th–9th century" },
    { question: "Who built the famous Changu Narayan Temple?", options: ["King Mandev", "King Amshuverma", "King Manadev", "King Shiva Deva"], answer: "King Mandev" },
    { question: "When did the People's Movement II (Jana Andolan II) take place?", options: ["2004", "2005", "2006", "2007"], answer: "2006" },
    { question: "Who was the last King of Nepal?", options: ["King Birendra", "King Gyanendra", "King Mahendra", "King Tribhuvan"], answer: "King Gyanendra" },
    { question: "In which year did the tragic Royal Palace massacre occur?", options: ["1999", "2000", "2001", "2002"], answer: "2001" }
  ],

  nepal: [
    { question: "What is the capital of Nepal?", options: ["Pokhara", "Lalitpur", "Kathmandu", "Biratnagar"], answer: "Kathmandu" },
    { question: "Which is the highest mountain in the world, located in Nepal?", options: ["K2", "Kanchenjunga", "Mount Everest", "Lhotse"], answer: "Mount Everest" },
    { question: "What is the national flower of Nepal?", options: ["Marigold", "Rhododendron", "Lotus", "Sunflower"], answer: "Rhododendron" },
    { question: "What is the national animal of Nepal?", options: ["Tiger", "Elephant", "Cow", "Rhinoceros"], answer: "Cow" },
    { question: "Which river is considered the holiest in Nepal?", options: ["Koshi", "Gandaki", "Bagmati", "Karnali"], answer: "Bagmati" },
    { question: "What is the official language of Nepal?", options: ["Hindi", "Nepali", "Maithili", "Newari"], answer: "Nepali" },
    { question: "Which famous lake in Pokhara is also called 'Lake of the Gods'?", options: ["Rara Lake", "Phewa Lake", "Begnas Lake", "Tilicho Lake"], answer: "Phewa Lake" },
    { question: "What is the currency of Nepal?", options: ["Rupee", "Nepalese Rupee", "Paisa", "Taka"], answer: "Nepalese Rupee" },
    { question: "Which festival is known as the 'festival of lights' in Nepal?", options: ["Dashain", "Tihar", "Holi", "Chhath"], answer: "Tihar" },
    { question: "What is the longest river entirely within Nepal?", options: ["Karnali", "Gandaki", "Koshi", "Mahakali"], answer: "Karnali" },
    { question: "Which UNESCO World Heritage Site is in the Kathmandu Valley?", options: ["Pashupatinath", "Lumbini", "Chitwan", "Sagarmatha"], answer: "Pashupatinath" },
    { question: "Where was Lord Buddha born?", options: ["Bodh Gaya", "Lumbini", "Sarnath", "Kushinagar"], answer: "Lumbini" },
    { question: "What is the traditional greeting in Nepal?", options: ["Hello", "Namaste", "Salaam", "Hi"], answer: "Namaste" },
    { question: "Which national park in Nepal is famous for one-horned rhinoceros?", options: ["Sagarmatha", "Chitwan", "Bardiya", "Rara"], answer: "Chitwan" },
    { question: "How many provinces does Nepal have?", options: ["5", "6", "7", "8"], answer: "7" },
    { question: "What is the name of the famous temple of Lord Shiva in Kathmandu?", options: ["Swayambhunath", "Pashupatinath", "Boudhanath", "Changu Narayan"], answer: "Pashupatinath" },
    { question: "Which mountain is also known as 'Sagarmatha' in Nepal?", options: ["K2", "Kanchenjunga", "Mount Everest", "Annapurna"], answer: "Mount Everest" },
    { question: "What is the main crop of the Terai region?", options: ["Wheat", "Rice", "Barley", "Millet"], answer: "Rice" },
    { question: "Which is the largest lake in Nepal?", options: ["Phewa Lake", "Rara Lake", "Tilicho Lake", "Begnas Lake"], answer: "Rara Lake" },
    { question: "What is the traditional Newari festival of Kathmandu Valley?", options: ["Indra Jatra", "Dashain", "Tihar", "Holi"], answer: "Indra Jatra" },
    { question: "Which pass connects Nepal with Tibet?", options: ["Nathu La", "Kodari", "Rohtang", "Shipki"], answer: "Kodari" },
    { question: "What is the approximate population of Nepal (in millions)?", options: ["Around 25", "Around 28", "Around 30", "Around 35"], answer: "Around 30" },
    { question: "Which is the second highest peak in Nepal?", options: ["K2", "Kanchenjunga", "Lhotse", "Makalu"], answer: "Kanchenjunga" },
    { question: "What is the main religion of Nepal?", options: ["Buddhism", "Hinduism", "Islam", "Christianity"], answer: "Hinduism" },
    { question: "Which district is Lumbini located in?", options: ["Chitwan", "Rupandehi", "Nawalparasi", "Kapilvastu"], answer: "Rupandehi" },
    { question: "What is the traditional Newari rice beer called?", options: ["Raksi", "Tongba", "Chyang", "Jaand"], answer: "Chyang" }
  ],

  geography: [
    { question: "What is the capital of Japan?", options: ["Seoul", "Beijing", "Tokyo", "Bangkok"], answer: "Tokyo" },
    { question: "Which is the longest river in the world?", options: ["Amazon", "Nile", "Yangtze", "Mississippi"], answer: "Nile" },
    { question: "Which desert is the largest in the world?", options: ["Gobi", "Sahara", "Arabian", "Antarctic"], answer: "Antarctic" },
    { question: "What is the smallest country in the world?", options: ["Monaco", "Vatican City", "San Marino", "Liechtenstein"], answer: "Vatican City" },
    { question: "Which mountain is the highest in the world?", options: ["K2", "Mount Everest", "Kilimanjaro", "Denali"], answer: "Mount Everest" },
    { question: "Which country has the most population?", options: ["India", "USA", "China", "Indonesia"], answer: "India" },
    { question: "The Suez Canal connects which two bodies of water?", options: ["Atlantic and Pacific", "Mediterranean and Red Sea", "Black Sea and Mediterranean", "Indian Ocean and Pacific"], answer: "Mediterranean and Red Sea" },
    { question: "What is the capital of Australia?", options: ["Sydney", "Melbourne", "Canberra", "Brisbane"], answer: "Canberra" },
    { question: "Which continent has the most countries?", options: ["Asia", "Africa", "Europe", "South America"], answer: "Africa" },
    { question: "The Amazon rainforest is primarily in which country?", options: ["Colombia", "Peru", "Brazil", "Venezuela"], answer: "Brazil" },
    { question: "What is the capital of Canada?", options: ["Toronto", "Vancouver", "Ottawa", "Montreal"], answer: "Ottawa" },
    { question: "Which sea is the Dead Sea?", options: ["Freshwater lake", "Salt lake", "Ocean", "River"], answer: "Salt lake" },
    { question: "Which country has the most islands?", options: ["Indonesia", "Philippines", "Sweden", "Finland"], answer: "Sweden" },
    { question: "What is the capital of South Korea?", options: ["Busan", "Seoul", "Incheon", "Daegu"], answer: "Seoul" },
    { question: "Which strait separates Europe from Africa?", options: ["Bering", "Gibraltar", "Malacca", "Hormuz"], answer: "Gibraltar" },
    { question: "What is the largest country in Africa by area?", options: ["Nigeria", "Egypt", "Algeria", "Sudan"], answer: "Algeria" },
    { question: "Which river flows through Paris?", options: ["Rhine", "Seine", "Thames", "Danube"], answer: "Seine" },
    { question: "What is the capital of New Zealand?", options: ["Auckland", "Wellington", "Christchurch", "Hamilton"], answer: "Wellington" },
    { question: "Which country is the Taj Mahal in?", options: ["Pakistan", "Bangladesh", "India", "Nepal"], answer: "India" },
    { question: "What is the longest river in Europe?", options: ["Danube", "Rhine", "Volga", "Seine"], answer: "Volga" },
    { question: "Which ocean is the Bermuda Triangle in?", options: ["Pacific", "Indian", "Atlantic", "Arctic"], answer: "Atlantic" },
    { question: "What is the capital of Argentina?", options: ["São Paulo", "Lima", "Buenos Aires", "Santiago"], answer: "Buenos Aires" },
    { question: "Which country is Mount Kilimanjaro in?", options: ["Kenya", "Uganda", "Tanzania", "Ethiopia"], answer: "Tanzania" },
    { question: "What is the only sea with no coastline?", options: ["Mediterranean", "Sargasso Sea", "Red Sea", "Black Sea"], answer: "Sargasso Sea" },
    { question: "Which country is both in Europe and Asia?", options: ["Egypt", "Turkey", "Russia", "Indonesia"], answer: "Turkey" }
  ],

  literature: [
    { question: "Who wrote 'Romeo and Juliet'?", options: ["Charles Dickens", "Jane Austen", "William Shakespeare", "Mark Twain"], answer: "William Shakespeare" },
    { question: "In 'Harry Potter', what is the name of Harry's owl?", options: ["Errol", "Hedwig", "Pigwidgeon", "Scabbers"], answer: "Hedwig" },
    { question: "Who wrote 'Pride and Prejudice'?", options: ["Emily Brontë", "Jane Austen", "Charlotte Brontë", "George Eliot"], answer: "Jane Austen" },
    { question: "What is the first book of the Bible?", options: ["Exodus", "Genesis", "Leviticus", "Numbers"], answer: "Genesis" },
    { question: "Who wrote '1984'?", options: ["Aldous Huxley", "George Orwell", "Ray Bradbury", "H.G. Wells"], answer: "George Orwell" },
    { question: "Which character said 'To be or not to be'?", options: ["Macbeth", "King Lear", "Hamlet", "Othello"], answer: "Hamlet" },
    { question: "Who wrote 'The Great Gatsby'?", options: ["Ernest Hemingway", "F. Scott Fitzgerald", "John Steinbeck", "William Faulkner"], answer: "F. Scott Fitzgerald" },
    { question: "In 'The Lord of the Rings', who is the main bearer of the One Ring?", options: ["Gandalf", "Aragorn", "Frodo", "Sam"], answer: "Frodo" },
    { question: "Who wrote 'Alice's Adventures in Wonderland'?", options: ["C.S. Lewis", "J.M. Barrie", "Lewis Carroll", "Roald Dahl"], answer: "Lewis Carroll" },
    { question: "Which poet wrote 'The Raven'?", options: ["Walt Whitman", "Emily Dickinson", "Edgar Allan Poe", "Robert Frost"], answer: "Edgar Allan Poe" },
    { question: "Who wrote 'Moby-Dick'?", options: ["Herman Melville", "Nathaniel Hawthorne", "Mark Twain", "Jack London"], answer: "Herman Melville" },
    { question: "Who created the character Sherlock Holmes?", options: ["Agatha Christie", "Arthur Conan Doyle", "Charles Dickens", "Oscar Wilde"], answer: "Arthur Conan Doyle" },
    { question: "Who wrote 'Jane Eyre'?", options: ["Jane Austen", "Charlotte Brontë", "Emily Brontë", "George Eliot"], answer: "Charlotte Brontë" },
    { question: "In 'The Hobbit', what is the name of the dragon?", options: ["Smaug", "Glaurung", "Ancalagon", "Scatha"], answer: "Smaug" },
    { question: "Who wrote 'Crime and Punishment'?", options: ["Tolstoy", "Dostoevsky", "Chekhov", "Pushkin"], answer: "Dostoevsky" },
    { question: "Which play has the line 'All the world's a stage'?", options: ["Hamlet", "Macbeth", "As You Like It", "King Lear"], answer: "As You Like It" },
    { question: "Who wrote 'The Catcher in the Rye'?", options: ["Jack Kerouac", "J.D. Salinger", "Kurt Vonnegut", "John Updike"], answer: "J.D. Salinger" },
    { question: "Which author wrote 'Dracula'?", options: ["Mary Shelley", "Bram Stoker", "Edgar Allan Poe", "H.P. Lovecraft"], answer: "Bram Stoker" },
    { question: "Who wrote 'Wuthering Heights'?", options: ["Charlotte Brontë", "Emily Brontë", "Anne Brontë", "Jane Austen"], answer: "Emily Brontë" },
    { question: "In 'Animal Farm', what type of animal is Napoleon?", options: ["Pig", "Horse", "Dog", "Donkey"], answer: "Pig" },
    { question: "Who wrote 'The Odyssey'?", options: ["Virgil", "Homer", "Sophocles", "Plato"], answer: "Homer" },
    { question: "Which Dickens novel features Ebenezer Scrooge?", options: ["Oliver Twist", "Great Expectations", "A Christmas Carol", "David Copperfield"], answer: "A Christmas Carol" },
    { question: "Who wrote 'Frankenstein'?", options: ["Bram Stoker", "Mary Shelley", "Edgar Allan Poe", "H.G. Wells"], answer: "Mary Shelley" },
    { question: "In 'To Kill a Mockingbird', what is the name of the lawyer father?", options: ["Atticus Finch", "Boo Radley", "Tom Robinson", "Bob Ewell"], answer: "Atticus Finch" },
    { question: "Who wrote 'The Picture of Dorian Gray'?", options: ["Oscar Wilde", "Charles Dickens", "Thomas Hardy", "Henry James"], answer: "Oscar Wilde" }
  ],

  music: [
    { question: "How many keys does a standard piano have?", options: ["66", "78", "88", "96"], answer: "88" },
    { question: "Which instrument is known as the 'king of instruments'?", options: ["Piano", "Organ", "Violin", "Guitar"], answer: "Organ" },
    { question: "What is the name of the Beatles' last album?", options: ["Let It Be", "Abbey Road", "Help!", "Revolver"], answer: "Abbey Road" },
    { question: "Which note is the first in the scale of C major?", options: ["A", "B", "C", "D"], answer: "C" },
    { question: "What does 'BPM' stand for in music?", options: ["Beats Per Minute", "Bass Piano Mode", "Bar Per Measure", "Beat Pattern Music"], answer: "Beats Per Minute" },
    { question: "Which band sang 'Bohemian Rhapsody'?", options: ["The Rolling Stones", "Led Zeppelin", "Queen", "Pink Floyd"], answer: "Queen" },
    { question: "How many strings does a standard violin have?", options: ["3", "4", "5", "6"], answer: "4" },
    { question: "What is the Italian term for 'loud' in music?", options: ["Piano", "Forte", "Largo", "Presto"], answer: "Forte" },
    { question: "Which composer went deaf later in life?", options: ["Mozart", "Bach", "Beethoven", "Chopin"], answer: "Beethoven" },
    { question: "What is the name of the instrument that uses reeds?", options: ["Trumpet", "Clarinet", "Flute", "Trombone"], answer: "Clarinet" },
    { question: "How many strings does a standard ukulele have?", options: ["3", "4", "5", "6"], answer: "4" },
    { question: "What is the Italian term for 'slow' in music?", options: ["Allegro", "Presto", "Adagio", "Vivace"], answer: "Adagio" },
    { question: "Which band had a hit with 'Smells Like Teen Spirit'?", options: ["Pearl Jam", "Nirvana", "Soundgarden", "Alice in Chains"], answer: "Nirvana" },
    { question: "What is the name of the percussion instrument with keys struck by mallets?", options: ["Xylophone", "Tambourine", "Bongo", "Maracas"], answer: "Xylophone" },
    { question: "Who is known as the 'King of Pop'?", options: ["Elvis Presley", "Michael Jackson", "Prince", "Freddie Mercury"], answer: "Michael Jackson" },
    { question: "How many notes are in a standard major scale?", options: ["6", "7", "8", "12"], answer: "8" },
    { question: "Which instrument is the largest in the string family?", options: ["Violin", "Viola", "Cello", "Double bass"], answer: "Double bass" },
    { question: "What does 'piano' mean in Italian (as a dynamic)?", options: ["Loud", "Soft", "Fast", "Slow"], answer: "Soft" },
    { question: "Who composed 'The Four Seasons'?", options: ["Bach", "Mozart", "Vivaldi", "Handel"], answer: "Vivaldi" },
    { question: "Which band performed 'Stairway to Heaven'?", options: ["The Who", "Led Zeppelin", "Black Sabbath", "Deep Purple"], answer: "Led Zeppelin" },
    { question: "What is the name of the symbol that raises a note by a half step?", options: ["Flat", "Sharp", "Natural", "Clef"], answer: "Sharp" },
    { question: "How many movements does a typical symphony have?", options: ["2", "3", "4", "5"], answer: "4" },
    { question: "Who wrote the opera 'The Magic Flute'?", options: ["Beethoven", "Mozart", "Wagner", "Verdi"], answer: "Mozart" },
    { question: "Which key has no sharps or flats?", options: ["G major", "F major", "C major", "D major"], answer: "C major" },
    { question: "What is a 'crescendo'?", options: ["Getting softer", "Getting louder", "Getting faster", "Getting slower"], answer: "Getting louder" }
  ],

  nature: [
    { question: "What is the largest land animal?", options: ["Elephant", "Rhinoceros", "Hippopotamus", "Giraffe"], answer: "Elephant" },
    { question: "Which bird is known for being unable to fly?", options: ["Penguin", "Ostrich", "Emu", "All of these"], answer: "All of these" },
    { question: "What is the process by which plants make food using sunlight?", options: ["Respiration", "Photosynthesis", "Digestion", "Fermentation"], answer: "Photosynthesis" },
    { question: "Which animal has the longest lifespan?", options: ["Elephant", "Galápagos tortoise", "Blue whale", "Parrot"], answer: "Galápagos tortoise" },
    { question: "What is the largest type of big cat?", options: ["Lion", "Tiger", "Jaguar", "Leopard"], answer: "Tiger" },
    { question: "Which tree do acorns come from?", options: ["Maple", "Oak", "Pine", "Birch"], answer: "Oak" },
    { question: "What is the fastest land animal?", options: ["Lion", "Cheetah", "Horse", "Antelope"], answer: "Cheetah" },
    { question: "Which gas do plants release during photosynthesis?", options: ["Carbon Dioxide", "Nitrogen", "Oxygen", "Hydrogen"], answer: "Oxygen" },
    { question: "What is a group of lions called?", options: ["Herd", "Pack", "Pride", "Flock"], answer: "Pride" },
    { question: "Which insect has the most complex eyes?", options: ["Ant", "Bee", "Dragonfly", "Butterfly"], answer: "Dragonfly" },
    { question: "What is a group of wolves called?", options: ["Herd", "Pack", "Pride", "Flock"], answer: "Pack" },
    { question: "Which animal can regenerate lost body parts?", options: ["Frog", "Starfish", "Snake", "Fish"], answer: "Starfish" },
    { question: "What is the only mammal that can truly fly?", options: ["Flying squirrel", "Bat", "Flying fish", "Sugar glider"], answer: "Bat" },
    { question: "Which flower is associated with remembrance?", options: ["Rose", "Poppy", "Lily", "Daisy"], answer: "Poppy" },
    { question: "What is the largest bird in the world?", options: ["Eagle", "Ostrich", "Albatross", "Condor"], answer: "Ostrich" },
    { question: "Which insect is known for its light production?", options: ["Bee", "Firefly", "Butterfly", "Dragonfly"], answer: "Firefly" },
    { question: "What is hibernation?", options: ["Migration", "Long sleep in winter", "Hunting at night", "Camouflage"], answer: "Long sleep in winter" },
    { question: "Which tree is known for its syrup?", options: ["Oak", "Maple", "Birch", "Pine"], answer: "Maple" },
    { question: "What is the smallest bird in the world?", options: ["Sparrow", "Hummingbird", "Finch", "Wren"], answer: "Hummingbird" },
    { question: "Which animal has the longest neck?", options: ["Elephant", "Giraffe", "Ostrich", "Camel"], answer: "Giraffe" },
    { question: "What is a group of fish called?", options: ["Herd", "School", "Flock", "Pack"], answer: "School" },
    { question: "Which plant is carnivorous?", options: ["Sunflower", "Venus flytrap", "Rose", "Tulip"], answer: "Venus flytrap" },
    { question: "What is the largest reptile in the world?", options: ["Komodo dragon", "Saltwater crocodile", "Anaconda", "Python"], answer: "Saltwater crocodile" },
    { question: "Which bird is a symbol of peace?", options: ["Eagle", "Dove", "Owl", "Swan"], answer: "Dove" },
    { question: "What is the process of a caterpillar becoming a butterfly called?", options: ["Hibernation", "Metamorphosis", "Migration", "Molting"], answer: "Metamorphosis" }
  ],

  space: [
    { question: "What is the closest star to Earth?", options: ["Proxima Centauri", "The Sun", "Alpha Centauri", "Sirius"], answer: "The Sun" },
    { question: "Which planet is known as the Morning Star?", options: ["Mars", "Jupiter", "Venus", "Mercury"], answer: "Venus" },
    { question: "What is the name of our galaxy?", options: ["Andromeda", "Milky Way", "Triangulum", "Sombrero"], answer: "Milky Way" },
    { question: "Who was the first person to walk on the Moon?", options: ["Yuri Gagarin", "Neil Armstrong", "Buzz Aldrin", "John Glenn"], answer: "Neil Armstrong" },
    { question: "What is a light-year?", options: ["Time", "Distance", "Speed", "Brightness"], answer: "Distance" },
    { question: "Which planet has the most moons?", options: ["Jupiter", "Saturn", "Uranus", "Neptune"], answer: "Saturn" },
    { question: "What is a black hole?", options: ["A dark star", "A region with very strong gravity", "A hole in space", "A type of nebula"], answer: "A region with very strong gravity" },
    { question: "In which year did the first human go to space?", options: ["1957", "1961", "1969", "1971"], answer: "1961" },
    { question: "What is the largest planet in our solar system?", options: ["Saturn", "Jupiter", "Uranus", "Neptune"], answer: "Jupiter" },
    { question: "Which spacecraft has left our solar system?", options: ["Voyager 1", "Hubble", "Cassini", "New Horizons"], answer: "Voyager 1" },
    { question: "What is the closest planet to the Sun?", options: ["Venus", "Mercury", "Mars", "Earth"], answer: "Mercury" },
    { question: "Which planet is known for its Great Red Spot?", options: ["Mars", "Jupiter", "Saturn", "Neptune"], answer: "Jupiter" },
    { question: "What is the name of the telescope launched by NASA in 2021?", options: ["Hubble", "James Webb", "Spitzer", "Kepler"], answer: "James Webb" },
    { question: "How long does it take Earth to orbit the Sun?", options: ["30 days", "365 days", "24 hours", "12 months"], answer: "365 days" },
    { question: "What is a supernova?", options: ["A new star", "Explosion of a dying star", "A type of planet", "A black hole"], answer: "Explosion of a dying star" },
    { question: "Which planet has rings that are easily visible from Earth?", options: ["Jupiter", "Saturn", "Uranus", "Neptune"], answer: "Saturn" },
    { question: "What is the Moon's phase when it is fully lit?", options: ["New moon", "Full moon", "Half moon", "Crescent"], answer: "Full moon" },
    { question: "Who was the first person in space?", options: ["Neil Armstrong", "John Glenn", "Yuri Gagarin", "Alan Shepard"], answer: "Yuri Gagarin" },
    { question: "What is the asteroid belt located between?", options: ["Earth and Mars", "Mars and Jupiter", "Jupiter and Saturn", "Saturn and Uranus"], answer: "Mars and Jupiter" },
    { question: "What is the Sun primarily made of?", options: ["Helium", "Hydrogen", "Oxygen", "Carbon"], answer: "Hydrogen" },
    { question: "Which planet is known as the 'Red Planet'?", options: ["Venus", "Mars", "Jupiter", "Saturn"], answer: "Mars" },
    { question: "What is the name of NASA's Mars rover that landed in 2021?", options: ["Curiosity", "Perseverance", "Opportunity", "Spirit"], answer: "Perseverance" },
    { question: "How many planets are in our solar system?", options: ["7", "8", "9", "10"], answer: "8" },
    { question: "What causes the phases of the Moon?", options: ["Earth's shadow", "Moon's orbit around Earth", "Sun's position", "Rotation of Moon"], answer: "Moon's orbit around Earth" },
    { question: "Which dwarf planet was reclassified from a planet in 2006?", options: ["Ceres", "Pluto", "Eris", "Makemake"], answer: "Pluto" }
  ],

  english: [
    { question: "What is a noun?", options: ["A doing word", "A naming word", "A describing word", "A connecting word"], answer: "A naming word" },
    { question: "Which punctuation ends a question?", options: [".", "?", "!", ","], answer: "?" },
    { question: "What is the past tense of 'go'?", options: ["goed", "went", "gone", "going"], answer: "went" },
    { question: "Which word is an adjective in 'The big dog'?", options: ["The", "big", "dog", "none"], answer: "big" },
    { question: "What is a synonym for 'happy'?", options: ["Sad", "Joyful", "Angry", "Tired"], answer: "Joyful" },
    { question: "Which is a correct plural?", options: ["childs", "children", "childes", "child"], answer: "children" },
    { question: "What do we call a word that describes a verb?", options: ["Adjective", "Adverb", "Noun", "Pronoun"], answer: "Adverb" },
    { question: "Which sentence is correct?", options: ["He don't like it", "He doesn't like it", "He not like it", "He no like it"], answer: "He doesn't like it" },
    { question: "What is the opposite of 'begin'?", options: ["Start", "End", "Continue", "Pause"], answer: "End" },
    { question: "Which is a conjunction?", options: ["and", "quickly", "beautiful", "under"], answer: "and" },
    { question: "What is the comparative form of 'good'?", options: ["gooder", "more good", "better", "best"], answer: "better" },
    { question: "Which word is misspelled?", options: ["receive", "recieve", "believe", "achieve"], answer: "recieve" },
    { question: "What is a paragraph?", options: ["A single sentence", "A group of related sentences", "A single word", "A punctuation mark"], answer: "A group of related sentences" },
    { question: "What do quotation marks indicate?", options: ["A question", "Someone's exact words", "A pause", "An exclamation"], answer: "Someone's exact words" },
    { question: "Which is the correct contraction for 'they are'?", options: ["their", "there", "they're", "theyr"], answer: "they're" },
    { question: "What is a verb?", options: ["A naming word", "An action or state word", "A describing word", "A place word"], answer: "An action or state word" },
    { question: "Which is a proper noun?", options: ["city", "London", "country", "river"], answer: "London" },
    { question: "What is the past participle of 'write'?", options: ["wrote", "written", "writed", "writing"], answer: "written" },
    { question: "What does 'prefix' mean?", options: ["Something at the end of a word", "Something at the start of a word", "The root word", "A synonym"], answer: "Something at the start of a word" },
    { question: "Which is an example of alliteration?", options: ["Big and small", "Peter Piper picked", "Run quickly", "The cat sat"], answer: "Peter Piper picked" },
    { question: "What is a simile?", options: ["A comparison using like or as", "A direct comparison", "A sound word", "An exaggeration"], answer: "A comparison using like or as" },
    { question: "Which word is a pronoun?", options: ["run", "she", "beautiful", "quickly"], answer: "she" },
    { question: "What is the main idea of a passage?", options: ["A small detail", "The central point", "The title only", "The first word"], answer: "The central point" },
    { question: "Which is the correct spelling?", options: ["occured", "occurred", "ocured", "occurd"], answer: "occurred" },
    { question: "What is an antonym?", options: ["A word that means the same", "A word that means the opposite", "A describing word", "A plural form"], answer: "A word that means the opposite" }
  ],

  socialStudies: [
    { question: "What is democracy?", options: ["Rule by one person", "Rule by the people", "Rule by the military", "Rule by religion"], answer: "Rule by the people" },
    { question: "What is the capital of India?", options: ["Mumbai", "Kolkata", "New Delhi", "Chennai"], answer: "New Delhi" },
    { question: "Which continent is Egypt in?", options: ["Asia", "Africa", "Europe", "South America"], answer: "Africa" },
    { question: "What is a constitution?", options: ["A type of government", "A set of fundamental laws", "A political party", "A court"], answer: "A set of fundamental laws" },
    { question: "Who was the first Prime Minister of India?", options: ["Mahatma Gandhi", "Jawaharlal Nehru", "Sardar Patel", "Subhas Chandra Bose"], answer: "Jawaharlal Nehru" },
    { question: "What is GDP?", options: ["Gross Domestic Product", "General Development Plan", "Global Data Protocol", "Government Direct Policy"], answer: "Gross Domestic Product" },
    { question: "Which ocean is the largest?", options: ["Atlantic", "Indian", "Pacific", "Arctic"], answer: "Pacific" },
    { question: "What is citizenship?", options: ["Living in a country", "Legal membership in a country", "Traveling abroad", "Speaking a language"], answer: "Legal membership in a country" },
    { question: "When did the United Nations form?", options: ["1942", "1945", "1950", "1939"], answer: "1945" },
    { question: "What is inflation?", options: ["Rise in prices over time", "Fall in prices", "Stable economy", "New currency"], answer: "Rise in prices over time" },
    { question: "Which country has the most people?", options: ["China", "India", "USA", "Indonesia"], answer: "India" },
    { question: "What is a republic?", options: ["Rule by a king", "A country with an elected head of state", "A dictatorship", "A colony"], answer: "A country with an elected head of state" },
    { question: "What does 'secular' mean?", options: ["Religious", "Not favoring any religion", "Military rule", "Royal rule"], answer: "Not favoring any religion" },
    { question: "Which river is sacred in India?", options: ["Nile", "Ganges", "Amazon", "Thames"], answer: "Ganges" },
    { question: "What is human rights?", options: ["Rights only for some", "Basic rights for all humans", "Government rights", "Property rights"], answer: "Basic rights for all humans" },
    { question: "What is the role of the judiciary?", options: ["To make laws", "To interpret and apply laws", "To run elections", "To lead the army"], answer: "To interpret and apply laws" },
    { question: "Which is a landlocked country?", options: ["India", "Nepal", "Bangladesh", "Sri Lanka"], answer: "Nepal" },
    { question: "What is culture?", options: ["Only food", "Beliefs, customs, and arts of a group", "Only language", "Only clothes"], answer: "Beliefs, customs, and arts of a group" },
    { question: "What is migration?", options: ["Staying in one place", "Movement of people from one place to another", "A type of bird", "A holiday"], answer: "Movement of people from one place to another" },
    { question: "Which organization works for world peace?", options: ["WTO", "UN", "IMF", "WHO"], answer: "UN" },
    { question: "What is a census?", options: ["A vote", "Official count of population", "A tax", "A law"], answer: "Official count of population" },
    { question: "What is federalism?", options: ["Rule by one central government", "Sharing power between central and state governments", "Rule by states only", "No government"], answer: "Sharing power between central and state governments" },
    { question: "Which continent has the most countries?", options: ["Asia", "Europe", "Africa", "South America"], answer: "Africa" },
    { question: "What is equality?", options: ["Some people get more", "Treating everyone fairly", "Only rich people matter", "No rules"], answer: "Treating everyone fairly" },
    { question: "What is sustainable development?", options: ["Development that harms the environment", "Development that meets present needs without harming future generations", "No development", "Fast development only"], answer: "Development that meets present needs without harming future generations" }
  ],

  basketball: [
    { question: "How many players from each team are on the court in basketball?", options: ["4", "5", "6", "7"], answer: "5" },
    { question: "How many points is a free throw worth?", options: ["1", "2", "3", "4"], answer: "1" },
    { question: "What is it called when a player dribbles with both hands?", options: ["Double dribble", "Travel", "Foul", "Turnover"], answer: "Double dribble" },
    { question: "Which country is basketball believed to have originated?", options: ["UK", "USA", "Canada", "France"], answer: "USA" },
    { question: "How many points is a shot from inside the arc worth?", options: ["1", "2", "3", "4"], answer: "2" },
    { question: "What is the NBA?", options: ["National Basketball Association", "National Ball Association", "New Basketball League", "North American Basketball"], answer: "National Basketball Association" },
    { question: "How long is an NBA quarter?", options: ["8 minutes", "10 minutes", "12 minutes", "15 minutes"], answer: "12 minutes" },
    { question: "What is a 'triple-double'?", options: ["Three points", "Double score", "Reaching double digits in 3 stats", "Three fouls"], answer: "Reaching double digits in 3 stats" },
    { question: "Which shot is worth 3 points?", options: ["Layup", "Free throw", "Shot from behind the three-point line", "Dunk"], answer: "Shot from behind the three-point line" },
    { question: "What is a 'rebound'?", options: ["A type of pass", "Getting the ball after a missed shot", "A foul", "A timeout"], answer: "Getting the ball after a missed shot" },
    { question: "How many fouls before a player is disqualified in NBA?", options: ["4", "5", "6", "7"], answer: "6" },
    { question: "What is the diameter of a basketball hoop in inches?", options: ["16", "18", "20", "22"], answer: "18" },
    { question: "Who invented basketball?", options: ["Michael Jordan", "James Naismith", "Larry Bird", "Magic Johnson"], answer: "James Naismith" },
    { question: "What is 'traveling'?", options: ["Moving without dribbling", "Going abroad", "A type of pass", "A shot"], answer: "Moving without dribbling" },
    { question: "How many seconds can a player hold the ball without dribbling (NBA)?", options: ["3", "5", "7", "10"], answer: "5" },
    { question: "What is a 'block'?", options: ["A type of pass", "Deflecting an opponent's shot", "A foul", "A rebound"], answer: "Deflecting an opponent's shot" },
    { question: "Which country has won the most Olympic gold in men's basketball?", options: ["Spain", "USA", "Argentina", "Serbia"], answer: "USA" },
    { question: "What is an 'assist'?", options: ["A type of shot", "A pass that leads to a score", "A foul", "A rebound"], answer: "A pass that leads to a score" },
    { question: "How high is the basketball hoop from the floor (feet)?", options: ["8", "9", "10", "11"], answer: "10" },
    { question: "What is a 'fast break'?", options: ["A quick attack before defense sets", "A slow play", "A timeout", "A foul"], answer: "A quick attack before defense sets" },
    { question: "Which position typically brings the ball up the court?", options: ["Center", "Power forward", "Point guard", "Small forward"], answer: "Point guard" },
    { question: "What is a 'technical foul'?", options: ["A physical foul", "A non-contact violation/unsportsmanlike conduct", "A time violation", "A scoring play"], answer: "A non-contact violation/unsportsmanlike conduct" },
    { question: "How many quarters in a standard basketball game?", options: ["2", "3", "4", "5"], answer: "4" },
    { question: "What is a 'dunk'?", options: ["A long shot", "Slamming the ball through the hoop", "A pass", "A free throw"], answer: "Slamming the ball through the hoop" },
    { question: "Which team has won the most NBA championships?", options: ["Lakers", "Celtics", "Bulls", "Warriors"], answer: "Celtics" },
    { question: "What is 'overtime'?", options: ["Extra period when game is tied", "Time out", "Half time", "Warm-up"], answer: "Extra period when game is tied" }
  ],

  olympics: [
    { question: "How often are the Summer Olympics held?", options: ["Every 2 years", "Every 3 years", "Every 4 years", "Every 5 years"], answer: "Every 4 years" },
    { question: "What do the five Olympic rings represent?", options: ["Five sports", "Five continents", "Five colors", "Five countries"], answer: "Five continents" },
    { question: "Where were the first modern Olympics held?", options: ["London", "Paris", "Athens", "Rome"], answer: "Athens" },
    { question: "In which year were the first modern Olympics held?", options: ["1892", "1896", "1900", "1904"], answer: "1896" },
    { question: "What is the Olympic motto?", options: ["Faster, Higher, Stronger", "Go for Gold", "One World", "Unity in Sport"], answer: "Faster, Higher, Stronger" },
    { question: "Which city hosted the 2020 Summer Olympics (held in 2021)?", options: ["Paris", "Tokyo", "London", "Rio"], answer: "Tokyo" },
    { question: "What color is the first ring in the Olympic symbol?", options: ["Red", "Blue", "Yellow", "Green"], answer: "Blue" },
    { question: "Which sport is NOT in the Summer Olympics?", options: ["Swimming", "Skiing", "Athletics", "Cycling"], answer: "Skiing" },
    { question: "What do athletes receive for first place?", options: ["Silver medal", "Gold medal", "Bronze medal", "Platinum medal"], answer: "Gold medal" },
    { question: "Which country has hosted the most Summer Olympics?", options: ["UK", "USA", "France", "Germany"], answer: "USA" },
    { question: "What is the Paralympics?", options: ["Olympics for youth", "Olympics for athletes with disabilities", "Winter Olympics", "Regional Olympics"], answer: "Olympics for athletes with disabilities" },
    { question: "In which city will the 2028 Summer Olympics be held?", options: ["Paris", "Los Angeles", "London", "Sydney"], answer: "Los Angeles" },
    { question: "Which flame is lit at the start of the Olympics?", options: ["Olympic torch", "Stadium flame", "Victory flame", "Peace flame"], answer: "Olympic torch" },
    { question: "What is the marathon distance in kilometers (approx)?", options: ["40 km", "41 km", "42 km", "43 km"], answer: "42 km" },
    { question: "Which country won the most medals at the 2020 Tokyo Olympics?", options: ["China", "USA", "Japan", "UK"], answer: "USA" },
    { question: "What does IOC stand for?", options: ["International Olympic Committee", "International Sports Council", "Olympic Sports Committee", "World Olympic Association"], answer: "International Olympic Committee" },
    { question: "Which event is known as the 'King of Sports' in Olympics?", options: ["Swimming", "Athletics (Track and Field)", "Gymnastics", "Cycling"], answer: "Athletics (Track and Field)" },
    { question: "Where is the Olympic flame lit before each Games?", options: ["Athens", "Olympia", "Rome", "Paris"], answer: "Olympia" },
    { question: "How many sports are in the Summer Olympics (approx)?", options: ["28", "33", "40", "50"], answer: "33" },
    { question: "What is the Winter Olympics?", options: ["Olympics in cold countries", "Olympics for winter sports", "Olympics at night", "Junior Olympics"], answer: "Olympics for winter sports" },
    { question: "Which country has never missed a Summer Olympics?", options: ["USA", "UK", "Greece", "France"], answer: "Greece" },
    { question: "What is a 'decathlon'?", options: ["10-event athletics competition", "A race", "A team sport", "A swimming event"], answer: "10-event athletics competition" },
    { question: "Which city hosted the 2016 Summer Olympics?", options: ["London", "Beijing", "Rio de Janeiro", "Tokyo"], answer: "Rio de Janeiro" },
    { question: "What do the Olympic rings' colors (with white background) include?", options: ["Only blue", "Blue, black, red, yellow, green", "Only primary colors", "Rainbow"], answer: "Blue, black, red, yellow, green" },
    { question: "Which sport awards the most medals at the Olympics?", options: ["Swimming", "Athletics", "Gymnastics", "Cycling"], answer: "Swimming" },
    { question: "What is the Olympic Truce?", options: ["A ceasefire during Games", "A type of event", "A medal", "A record"], answer: "A ceasefire during Games" }
  ],

  sportsGeneral: [
    { question: "How many players are in a rugby union team on the field?", options: ["11", "13", "15", "17"], answer: "15" },
    { question: "Which country is famous for sumo wrestling?", options: ["China", "Japan", "Korea", "Mongolia"], answer: "Japan" },
    { question: "What is the national sport of Canada?", options: ["Basketball", "Lacrosse", "Ice hockey", "Soccer"], answer: "Lacrosse" },
    { question: "In tennis, what is a 'grand slam'?", options: ["One major title", "Winning all four major tournaments", "A type of serve", "A tie-break"], answer: "Winning all four major tournaments" },
    { question: "Which sport uses a shuttlecock?", options: ["Tennis", "Badminton", "Squash", "Table tennis"], answer: "Badminton" },
    { question: "How many Grand Slam tournaments are there in tennis per year?", options: ["2", "3", "4", "5"], answer: "4" },
    { question: "What is the oldest sport in the Olympics?", options: ["Running", "Wrestling", "Boxing", "Swimming"], answer: "Running" },
    { question: "Which country invented table tennis?", options: ["China", "England", "Japan", "USA"], answer: "England" },
    { question: "What is a 'hat-trick' in sports?", options: ["Three goals/points in one game by one player", "Winning three games", "Three penalties", "Three assists"], answer: "Three goals/points in one game by one player" },
    { question: "Which sport is known as 'the beautiful game'?", options: ["Basketball", "Football (Soccer)", "Cricket", "Tennis"], answer: "Football (Soccer)" },
    { question: "How many players in a volleyball team on court?", options: ["5", "6", "7", "8"], answer: "6" },
    { question: "What is the Tour de France?", options: ["A football tournament", "A cycling race", "A tennis championship", "A marathon"], answer: "A cycling race" },
    { question: "Which sport has the Wimbledon championship?", options: ["Golf", "Tennis", "Cricket", "Badminton"], answer: "Tennis" },
    { question: "What is the diameter of a football (soccer) in cm?", options: ["20–22", "22–24", "24–26", "26–28"], answer: "22–24" },
    { question: "Which country has won the most FIFA World Cups?", options: ["Germany", "Italy", "Brazil", "Argentina"], answer: "Brazil" },
    { question: "What is 'offside' in football?", options: ["A position rule", "A foul", "A type of pass", "A throw-in"], answer: "A position rule" },
    { question: "How many Grand Slam titles did Roger Federer win?", options: ["18", "20", "22", "24"], answer: "20" },
    { question: "Which sport uses a 'bat' and 'ball'?", options: ["Cricket", "Hockey", "Golf", "All of these"], answer: "All of these" },
    { question: "What is the fastest land animal?", options: ["Lion", "Cheetah", "Horse", "Antelope"], answer: "Cheetah" },
    { question: "Which country hosted the 2022 FIFA World Cup?", options: ["Russia", "Qatar", "Brazil", "South Africa"], answer: "Qatar" },
    { question: "What is a 'penalty shootout'?", options: ["A type of foul", "Deciding a tie with penalty kicks", "A training drill", "A referee call"], answer: "Deciding a tie with penalty kicks" },
    { question: "Which sport has the Ryder Cup?", options: ["Tennis", "Golf", "Cricket", "Rugby"], answer: "Golf" },
    { question: "What is the national sport of USA?", options: ["Football", "Baseball", "Basketball", "No official one"], answer: "No official one" },
    { question: "How many points to win a set in tennis (unless deuce)?", options: ["4", "6", "8", "10"], answer: "6" },
    { question: "Which sport uses a 'putter'?", options: ["Tennis", "Golf", "Hockey", "Cricket"], answer: "Golf" },
    { question: "What is the Super Bowl?", options: ["Cricket final", "American football championship", "Basketball final", "Baseball final"], answer: "American football championship" }
  ],

  nepalGeography: [
    { question: "What is the capital of Nepal?", options: ["Pokhara", "Kathmandu", "Biratnagar", "Lalitpur"], answer: "Kathmandu" },
    { question: "Which is the highest mountain in the world, located in Nepal?", options: ["K2", "Mount Everest", "Kanchenjunga", "Lhotse"], answer: "Mount Everest" },
    { question: "How many provinces does Nepal have?", options: ["5", "6", "7", "8"], answer: "7" },
    { question: "Which river flows through Kathmandu Valley?", options: ["Koshi", "Bagmati", "Gandaki", "Karnali"], answer: "Bagmati" },
    { question: "Which is the largest lake in Nepal?", options: ["Phewa Lake", "Rara Lake", "Tilicho Lake", "Begnas Lake"], answer: "Rara Lake" },
    { question: "In which province is Lumbini located?", options: ["Province 1", "Province 2", "Lumbini Province", "Gandaki Province"], answer: "Lumbini Province" },
    { question: "Which district is Mount Everest in?", options: ["Sindhupalchok", "Solukhumbu", "Dolakha", "Ramechhap"], answer: "Solukhumbu" },
    { question: "What is the longest river entirely in Nepal?", options: ["Karnali", "Gandaki", "Koshi", "Mahakali"], answer: "Karnali" },
    { question: "Which national park is in the Terai?", options: ["Sagarmatha", "Chitwan", "Rara", "Langtang"], answer: "Chitwan" },
    { question: "What is the altitude of Kathmandu (approx in meters)?", options: ["1000", "1300", "1600", "2000"], answer: "1300" },
    { question: "Which pass connects Nepal with Tibet?", options: ["Nathu La", "Kodari", "Rohtang", "Shipki"], answer: "Kodari" },
    { question: "Which is the smallest district in Nepal by area?", options: ["Bhaktapur", "Lalitpur", "Kathmandu", "Kavrepalanchok"], answer: "Bhaktapur" },
    { question: "In which province is Pokhara?", options: ["Gandaki", "Lumbini", "Karnali", "Sudurpashchim"], answer: "Gandaki" },
    { question: "Which river forms part of the western border of Nepal?", options: ["Koshi", "Mahakali", "Gandaki", "Karnali"], answer: "Mahakali" },
    { question: "What is the highest lake in Nepal?", options: ["Phewa", "Rara", "Tilicho", "Begnas"], answer: "Tilicho" },
    { question: "Which mountain is entirely in Nepal (not on border)?", options: ["Everest", "Kanchenjunga", "Dhaulagiri", "Annapurna"], answer: "Dhaulagiri" },
    { question: "What is the climate of the Terai?", options: ["Alpine", "Subtropical", "Temperate", "Tundra"], answer: "Subtropical" },
    { question: "Which province has the most districts?", options: ["Karnali", "Sudurpashchim", "Bagmati", "Lumbini"], answer: "Karnali" },
    { question: "Where is the Kali Gandaki gorge?", options: ["Between Dhaulagiri and Annapurna", "Near Everest", "In Terai", "In Far West"], answer: "Between Dhaulagiri and Annapurna" },
    { question: "Which river is known as Saptakoshi?", options: ["Karnali", "Koshi", "Gandaki", "Bagmati"], answer: "Koshi" },
    { question: "What is the area of Nepal (approx sq km)?", options: ["120,000", "147,000", "180,000", "200,000"], answer: "147,000" },
    { question: "Which district is Janakpur in?", options: ["Sarlahi", "Dhanusha", "Mahottari", "Siraha"], answer: "Dhanusha" },
    { question: "What is the main geographical region between Himal and Terai?", options: ["Pahad (Hill)", "Mountain", "Valley", "Desert"], answer: "Pahad (Hill)" },
    { question: "Which lake is in Pokhara?", options: ["Rara", "Phewa", "Tilicho", "Fewa"], answer: "Phewa" },
    { question: "In which province is Chitwan National Park?", options: ["Bagmati", "Gandaki", "Lumbini", "Madhesh"], answer: "Bagmati" },
    { question: "What is the highest peak entirely in Nepal?", options: ["Everest", "Kanchenjunga", "Dhaulagiri", "Annapurna I"], answer: "Dhaulagiri" }
  ],

  nepalCulture: [
    { question: "What is the traditional greeting in Nepal?", options: ["Hello", "Namaste", "Salaam", "Hi"], answer: "Namaste" },
    { question: "What is the main religion in Nepal?", options: ["Buddhism", "Hinduism", "Islam", "Christianity"], answer: "Hinduism" },
    { question: "Which festival is known as 'Dashain'?", options: ["Festival of lights", "Vijaya Dashami", "New Year", "Harvest"], answer: "Vijaya Dashami" },
    { question: "What is the traditional Newari rice beer called?", options: ["Raksi", "Tongba", "Chyang", "Jaand"], answer: "Chyang" },
    { question: "Which ethnic group is associated with the Kathmandu Valley?", options: ["Tamang", "Newar", "Gurung", "Tharu"], answer: "Newar" },
    { question: "What is 'Roti' in Nepali context?", options: ["Rice", "Bread", "Curry", "Dal"], answer: "Bread" },
    { question: "Which dance is traditional in Nepal?", options: ["Bharatanatyam", "Lakhe dance", "Kathak", "Bhangra"], answer: "Lakhe dance" },
    { question: "What is the national dress of Nepal for men (traditional)?", options: ["Sari", "Daura Suruwal", "Lungi", "Kurta"], answer: "Daura Suruwal" },
    { question: "Which temple is dedicated to Lord Shiva in Kathmandu?", options: ["Swayambhunath", "Pashupatinath", "Boudhanath", "Changu Narayan"], answer: "Pashupatinath" },
    { question: "What is 'Tihar' also known as?", options: ["Dashain", "Dipawali", "Holi", "Maha Shivaratri"], answer: "Dipawali" },
    { question: "Which animal is considered sacred in Nepal?", options: ["Dog", "Cow", "Monkey", "Elephant"], answer: "Cow" },
    { question: "What is the traditional drum of the Newars?", options: ["Tabla", "Madal", "Dhimay", "Mridangam"], answer: "Dhimay" },
    { question: "Which festival involves worshipping brothers?", options: ["Dashain", "Tihar (Bhai Tika)", "Holi", "Chhath"], answer: "Tihar (Bhai Tika)" },
    { question: "What is 'Dal Bhat'?", options: ["Rice and lentils", "Bread and curry", "Meat dish", "Dessert"], answer: "Rice and lentils" },
    { question: "Which is a UNESCO site in the Kathmandu Valley?", options: ["Pashupatinath", "Lumbini", "Chitwan", "Sagarmatha"], answer: "Pashupatinath" },
    { question: "What is the national flower of Nepal?", options: ["Lotus", "Rhododendron", "Marigold", "Sunflower"], answer: "Rhododendron" },
    { question: "Which language is widely spoken in the hills?", options: ["Nepali", "Maithili", "Newari", "Nepali and others"], answer: "Nepali and others" },
    { question: "What is 'Mhendo' or 'Mheto' in Newar culture?", options: ["A festival", "A coming-of-age ceremony", "A dance", "A food"], answer: "A coming-of-age ceremony" },
    { question: "Which festival is the 'festival of colors'?", options: ["Dashain", "Tihar", "Holi", "Maha Shivaratri"], answer: "Holi" },
    { question: "What is the traditional alcohol made from rice/millet?", options: ["Chyang", "Raksi", "Tongba", "All of these"], answer: "Raksi" },
    { question: "Which stupa is one of the largest in the world?", options: ["Swayambhunath", "Boudhanath", "Namobuddha", "Lumbini"], answer: "Boudhanath" },
    { question: "What is 'Guthi'?", options: ["A food", "A traditional social organization", "A dance", "A temple"], answer: "A traditional social organization" },
    { question: "Which community is known for Gurkha soldiers?", options: ["Newar", "Tamang", "Gurung/Magar", "Tharu"], answer: "Gurung/Magar" },
    { question: "What is the Nepali calendar called?", options: ["Vikram Samvat", "Gregorian", "Lunar", "Solar"], answer: "Vikram Samvat" },
    { question: "Which day is 'Saturday' in Nepali?", options: ["Sanibar", "Somabar", "Mangalbar", "Budhabar"], answer: "Sanibar" },
    { question: "What is 'Puja'?", options: ["A dance", "Worship/offering", "A festival", "A food"], answer: "Worship/offering" }
  ],

  nepalFestivals: [
    { question: "When is Dashain usually celebrated?", options: ["March", "October", "December", "January"], answer: "October" },
    { question: "What is the last day of Dashain called?", options: ["Fulpati", "Vijaya Dashami", "Tika", "Navami"], answer: "Vijaya Dashami" },
    { question: "Which animal is sacrificed during Dashain?", options: ["Cow", "Buffalo", "Goat", "Goat and buffalo"], answer: "Goat and buffalo" },
    { question: "What is 'Tika' in Dashain?", options: ["A dance", "A mixture of rice, yogurt, vermillion put on forehead", "A song", "A food"], answer: "A mixture of rice, yogurt, vermillion put on forehead" },
    { question: "Which day of Tihar is for crows?", options: ["Day 1", "Day 2", "Day 3", "Day 4"], answer: "Day 1" },
    { question: "What is 'Laxmi Puja'?", options: ["Worship of goddess of wealth during Tihar", "A dance", "A food", "New Year"], answer: "Worship of goddess of wealth during Tihar" },
    { question: "Which festival is 'Bhai Tika' part of?", options: ["Dashain", "Tihar", "Holi", "Maha Shivaratri"], answer: "Tihar" },
    { question: "When is Holi celebrated?", options: ["October", "February/March", "December", "August"], answer: "February/March" },
    { question: "What is 'Maha Shivaratri'?", options: ["New Year", "Night of Lord Shiva", "Harvest festival", "Festival of lights"], answer: "Night of Lord Shiva" },
    { question: "Which festival is Indra Jatra associated with?", options: ["Newar", "Tharu", "Tamang", "Gurung"], answer: "Newar" },
    { question: "What is 'Chhath'?", options: ["A Hindu festival worshipping the sun", "A Buddhist festival", "New Year", "Harvest"], answer: "A Hindu festival worshipping the sun" },
    { question: "When is Buddha Jayanti celebrated?", options: ["Full moon of April/May", "October", "December", "January"], answer: "Full moon of April/May" },
    { question: "What is 'Losar'?", options: ["Hindu New Year", "Tibetan/Buddhist New Year", "Harvest festival", "Dashain"], answer: "Tibetan/Buddhist New Year" },
    { question: "Which community celebrates Sonam Lhosar?", options: ["Newar", "Tamang", "Tharu", "Gurung"], answer: "Tamang" },
    { question: "What is 'Gai Jatra'?", options: ["Cow festival", "Festival of lights", "New Year", "Harvest"], answer: "Cow festival" },
    { question: "When is Nepali New Year (Bikram Sambat) celebrated?", options: ["January 1", "Mid-April", "October", "December"], answer: "Mid-April" },
    { question: "What is 'Teej'?", options: ["A festival for women, fasting for husband's longevity", "Harvest", "New Year", "Dashain"], answer: "A festival for women, fasting for husband's longevity" },
    { question: "Which festival involves flying kites?", options: ["Dashain", "Tihar", "Holi", "Maha Shivaratri"], answer: "Dashain" },
    { question: "What is 'Janai Purnima'?", options: ["Sacred thread festival", "New Year", "Harvest", "Lights"], answer: "Sacred thread festival" },
    { question: "Which festival is 'Siti' or 'Sithi Nakha'?", options: ["Newar festival for cleaning water sources", "Dashain", "Tihar", "Holi"], answer: "Newar festival for cleaning water sources" },
    { question: "What is 'Yomari Punhi'?", options: ["Full moon when Yomari (dumpling) is eaten", "Dashain", "Tihar", "New Year"], answer: "Full moon when Yomari (dumpling) is eaten" },
    { question: "Which day is 'Goverdhan Puja' in Tihar?", options: ["Day 2", "Day 3", "Day 4", "Day 5"], answer: "Day 4" },
    { question: "What is 'Maghe Sankranti'?", options: ["Winter solstice festival", "New Year", "Dashain", "Tihar"], answer: "Winter solstice festival" },
    { question: "Which festival marks the start of the rice planting season in some areas?", options: ["Dashain", "Asar 15 (Ropain)", "Tihar", "Holi"], answer: "Asar 15 (Ropain)" },
    { question: "What is 'Kumar Sashthi'?", options: ["A Newar festival", "Dashain", "Tihar", "Holi"], answer: "A Newar festival" },
    { question: "Which festival is dedicated to dogs in Tihar?", options: ["Day 1", "Day 2 (Kukur Tihar)", "Day 3", "Day 4"], answer: "Day 2 (Kukur Tihar)" }
  ],

  worldHistory: [
    { question: "In which year did World War II end?", options: ["1943", "1944", "1945", "1946"], answer: "1945" },
    { question: "Who was the first President of the United States?", options: ["Thomas Jefferson", "George Washington", "John Adams", "Benjamin Franklin"], answer: "George Washington" },
    { question: "In which year did the Titanic sink?", options: ["1910", "1912", "1914", "1916"], answer: "1912" },
    { question: "Who discovered America in 1492?", options: ["Amerigo Vespucci", "Christopher Columbus", "Ferdinand Magellan", "Vasco da Gama"], answer: "Christopher Columbus" },
    { question: "When did World War I begin?", options: ["1912", "1914", "1916", "1918"], answer: "1914" },
    { question: "Which empire built the Taj Mahal?", options: ["British", "Mughal", "Maurya", "Gupta"], answer: "Mughal" },
    { question: "In which year did the Berlin Wall fall?", options: ["1987", "1989", "1991", "1993"], answer: "1989" },
    { question: "Who wrote the Declaration of Independence?", options: ["George Washington", "Thomas Jefferson", "Benjamin Franklin", "John Adams"], answer: "Thomas Jefferson" },
    { question: "Which ancient civilization built the pyramids at Giza?", options: ["Romans", "Greeks", "Egyptians", "Mesopotamians"], answer: "Egyptians" },
    { question: "When did the French Revolution begin?", options: ["1789", "1799", "1776", "1804"], answer: "1789" },
    { question: "Who was the first person to walk on the Moon?", options: ["Buzz Aldrin", "Neil Armstrong", "Yuri Gagarin", "John Glenn"], answer: "Neil Armstrong" },
    { question: "Which country gave the Statue of Liberty to the USA?", options: ["UK", "France", "Italy", "Spain"], answer: "France" },
    { question: "Who invented the printing press?", options: ["Benjamin Franklin", "Johannes Gutenberg", "Leonardo da Vinci", "Isaac Newton"], answer: "Johannes Gutenberg" },
    { question: "In which year did India gain independence?", options: ["1945", "1946", "1947", "1948"], answer: "1947" },
    { question: "Who was the British Prime Minister during most of WWII?", options: ["Neville Chamberlain", "Winston Churchill", "Clement Attlee", "Anthony Eden"], answer: "Winston Churchill" },
    { question: "Which ancient city was buried by Mount Vesuvius?", options: ["Athens", "Pompeii", "Rome", "Sparta"], answer: "Pompeii" },
    { question: "When did the Roman Empire (Western) fall?", options: ["376 AD", "410 AD", "476 AD", "500 AD"], answer: "476 AD" },
    { question: "Which empire was ruled by Genghis Khan?", options: ["Ottoman", "Mongol", "Persian", "Byzantine"], answer: "Mongol" },
    { question: "Who was Nelson Mandela?", options: ["Prime Minister of UK", "President of South Africa", "President of USA", "UN Secretary"], answer: "President of South Africa" },
    { question: "In which year did the American Civil War end?", options: ["1863", "1864", "1865", "1866"], answer: "1865" },
    { question: "Who was Cleopatra?", options: ["Roman Empress", "Egyptian Queen", "Greek Goddess", "Persian Queen"], answer: "Egyptian Queen" },
    { question: "When did the Holocaust occur?", options: ["WWI", "WWII", "Cold War", "Vietnam War"], answer: "WWII" },
    { question: "Which dynasty ruled China for centuries until 1912?", options: ["Ming", "Qing", "Tang", "Song"], answer: "Qing" },
    { question: "Who was the leader of the Soviet Union during WWII?", options: ["Lenin", "Stalin", "Khrushchev", "Trotsky"], answer: "Stalin" },
    { question: "In which century did the Renaissance begin in Europe?", options: ["12th", "14th", "16th", "18th"], answer: "14th" },
    { question: "What was the name of the first man in space?", options: ["Neil Armstrong", "Yuri Gagarin", "John Glenn", "Alan Shepard"], answer: "Yuri Gagarin" }
  ],

  artMovies: [
    { question: "Who painted the Mona Lisa?", options: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Michelangelo"], answer: "Leonardo da Vinci" },
    { question: "Which studio made 'Finding Nemo'?", options: ["DreamWorks", "Pixar", "Disney Animation", "Blue Sky"], answer: "Pixar" },
    { question: "What is the name of the wizard in 'The Wizard of Oz'?", options: ["Gandalf", "Oz", "Dumbledore", "Merlin"], answer: "Oz" },
    { question: "Who directed 'Titanic'?", options: ["Steven Spielberg", "James Cameron", "Christopher Nolan", "Ridley Scott"], answer: "James Cameron" },
    { question: "Which artist cut off his ear?", options: ["Picasso", "Vincent van Gogh", "Monet", "Rembrandt"], answer: "Vincent van Gogh" },
    { question: "What is the highest-grossing film of all time (approx)?", options: ["Titanic", "Avatar", "Avengers: Endgame", "Avatar 2"], answer: "Avatar" },
    { question: "Which art movement did Picasso help found?", options: ["Impressionism", "Cubism", "Surrealism", "Renaissance"], answer: "Cubism" },
    { question: "Who painted 'The Starry Night'?", options: ["Monet", "Vincent van Gogh", "Picasso", "Rembrandt"], answer: "Vincent van Gogh" },
    { question: "Which film won Best Picture at the first Oscars?", options: ["Wings", "Sunrise", "The Jazz Singer", "All Quiet on the Western Front"], answer: "Wings" },
    { question: "What is the Louvre?", options: ["A palace", "A museum in Paris", "A church", "A theatre"], answer: "A museum in Paris" },
    { question: "Who directed 'Jurassic Park'?", options: ["James Cameron", "Steven Spielberg", "George Lucas", "Ridley Scott"], answer: "Steven Spielberg" },
    { question: "Which artist painted the Sistine Chapel ceiling?", options: ["Leonardo", "Raphael", "Michelangelo", "Donatello"], answer: "Michelangelo" },
    { question: "What is 'Impressionism'?", options: ["A music style", "An art movement focusing on light and moment", "A film genre", "A dance"], answer: "An art movement focusing on light and moment" },
    { question: "Which film has the character Simba?", options: ["The Jungle Book", "The Lion King", "Madagascar", "Tarzan"], answer: "The Lion King" },
    { question: "Who painted 'The Persistence of Memory' (melting clocks)?", options: ["Picasso", "Dali", "Magritte", "Van Gogh"], answer: "Dali" },
    { question: "Which country is Bollywood from?", options: ["Pakistan", "India", "Bangladesh", "Sri Lanka"], answer: "India" },
    { question: "What is the Oscar statuette made of?", options: ["Gold", "Bronze coated in gold", "Silver", "Platinum"], answer: "Bronze coated in gold" },
    { question: "Who directed 'Inception'?", options: ["Steven Spielberg", "Christopher Nolan", "David Fincher", "Ridley Scott"], answer: "Christopher Nolan" },
    { question: "Which artist is known for pop art and Campbell's soup?", options: ["Warhol", "Lichtenstein", "Haring", "Basquiat"], answer: "Warhol" },
    { question: "What is the name of the ship in 'Titanic'?", options: ["RMS Titanic", "SS Titanic", "HM Titanic", "MV Titanic"], answer: "RMS Titanic" },
    { question: "Who painted 'The Birth of Venus'?", options: ["Michelangelo", "Leonardo", "Raphael", "Botticelli"], answer: "Botticelli" },
    { question: "Which film won the most Oscars (11)?", options: ["Titanic", "Ben-Hur", "Lord of the Rings: Return of the King", "Ben-Hur, Titanic, Lord of the Rings"], answer: "Ben-Hur, Titanic, Lord of the Rings" },
    { question: "What is a 'musical' in film?", options: ["A film with songs and dance", "A silent film", "A documentary", "A horror film"], answer: "A film with songs and dance" },
    { question: "Who painted the 'Girl with a Pearl Earring'?", options: ["Rembrandt", "Vermeer", "Rubens", "Van Dyck"], answer: "Vermeer" },
    { question: "Which studio made 'Shrek'?", options: ["Pixar", "DreamWorks", "Disney", "Blue Sky"], answer: "DreamWorks" },
    { question: "What is the Golden Globe?", options: ["A film award", "A theatre award", "A music award", "A sports award"], answer: "A film award" },
    { question: "Who directed 'Avatar'?", options: ["Steven Spielberg", "James Cameron", "Ridley Scott", "Peter Jackson"], answer: "James Cameron" }
  ],

  currentAffairs: [
    { question: "Which country hosted the 2024 Summer Olympics?", options: ["Tokyo", "Paris", "Los Angeles", "London"], answer: "Paris" },
    { question: "What is COP?", options: ["Conference of the Parties (climate)", "Council of Presidents", "Committee on Peace", "Council of Nations"], answer: "Conference of the Parties (climate)" },
    { question: "Which disease did the WHO declare a pandemic in 2020?", options: ["SARS", "COVID-19", "MERS", "Ebola"], answer: "COVID-19" },
    { question: "What is the European Union's currency?", options: ["Pound", "Euro", "Franc", "Mark"], answer: "Euro" },
    { question: "Which country left the EU in 2020?", options: ["France", "UK", "Germany", "Italy"], answer: "UK" },
    { question: "What is NATO?", options: ["North Atlantic Treaty Organization", "Nuclear Arms Treaty", "Asian Trade Organization", "African Union"], answer: "North Atlantic Treaty Organization" },
    { question: "Which country has the most nuclear weapons (approx)?", options: ["China", "Russia", "USA", "North Korea"], answer: "Russia" },
    { question: "What is the UN Security Council?", options: ["A court", "A body with 5 permanent members for peace", "A health body", "A trade body"], answer: "A body with 5 permanent members for peace" },
    { question: "Which country is the largest by area?", options: ["USA", "China", "Russia", "Canada"], answer: "Russia" },
    { question: "What is GDP?", options: ["Gross Domestic Product", "Global Development Plan", "Government Data Policy", "General Debt Plan"], answer: "Gross Domestic Product" },
    { question: "Which organization heads global health?", options: ["UN", "WHO", "UNICEF", "WTO"], answer: "WHO" },
    { question: "What is climate change primarily linked to?", options: ["Volcanoes", "Greenhouse gas emissions", "Ocean currents only", "Solar flares"], answer: "Greenhouse gas emissions" },
    { question: "Which continent has the most people?", options: ["Europe", "Africa", "Asia", "North America"], answer: "Asia" },
    { question: "What is renewable energy?", options: ["Coal and oil", "Energy from sun, wind, water that can be replenished", "Nuclear only", "Gas only"], answer: "Energy from sun, wind, water that can be replenished" },
    { question: "Which country has the world's largest democracy by population?", options: ["USA", "India", "Indonesia", "Brazil"], answer: "India" },
    { question: "What is the G20?", options: ["20 countries' group for economic cooperation", "A sports league", "A military alliance", "A health body"], answer: "20 countries' group for economic cooperation" },
    { question: "Which virus caused a major outbreak in 2014-2016 in West Africa?", options: ["COVID-19", "Ebola", "Zika", "SARS"], answer: "Ebola" },
    { question: "What is cryptocurrency?", options: ["Government-issued money only", "Digital or virtual currency", "Gold-backed currency", "EU currency"], answer: "Digital or virtual currency" },
    { question: "Which country launched the first artificial satellite?", options: ["USA", "USSR/Russia", "China", "UK"], answer: "USSR/Russia" },
    { question: "What is AI?", options: ["Artificial Intelligence", "Advanced Internet", "Automated Industry", "American Institute"], answer: "Artificial Intelligence" },
    { question: "Which sea is the Suez Canal in?", options: ["Pacific", "Mediterranean/Red Sea region", "Atlantic", "Indian"], answer: "Mediterranean/Red Sea region" },
    { question: "What is the Paris Agreement?", options: ["Trade deal", "Climate agreement to limit warming", "Military pact", "Health treaty"], answer: "Climate agreement to limit warming" },
    { question: "Which social media company owns Instagram?", options: ["Google", "Meta (Facebook)", "Twitter", "Snap"], answer: "Meta (Facebook)" },
    { question: "What is 5G?", options: ["Fifth generation of mobile networks", "A type of car", "A vaccine", "A satellite"], answer: "Fifth generation of mobile networks" },
    { question: "Which country has the most Olympic medals overall?", options: ["China", "USA", "Russia/USSR", "UK"], answer: "USA" },
    { question: "What is the IMF?", options: ["International Monetary Fund", "International Military Force", "Internet Media Foundation", "International Music Fund"], answer: "International Monetary Fund" }
  ]
};

// Mixed challenge: script.js shuffles all categories and picks 10 random questions each game
